steps:
  build-latest:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: latest
      platforms: linux/amd64, linux/arm64
    secrets: [ docker_username, docker_password ]
when:
  branch: main
  event: push
